name: Copy Processor Images to DockerHub on Release
on:
  push:
    tags:
      - aptos-indexer-processors-v*

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies and Run Linter
        uses: ./.github/actions/dep_install_and_lint
        with:
          working-directory: .

      - name: Run Integration Tests for Specific Crate
        run: cargo test --manifest-path integration-tests/Cargo.toml
        working-directory: .

  copy-processor-images:
    # Run on a machine with more local storage for large docker images
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - uses: aptos-labs/aptos-core/.github/actions/docker-setup@main
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Login to Docker Hub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # pin@v2
        with:
          username: ${{ secrets.ENV_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ENV_DOCKERHUB_PASSWORD }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin https://github.com/pnpm/action-setup/releases/tag/v4.0.0
        with:
          run_install: false
          package_json_file: scripts/package.json

      - run: pnpm install --frozen-lockfile
        working-directory: scripts

      - name: Release Images
        env:
          FORCE_COLOR: 3 # Force color output as per https://github.com/google/zx#using-github-actions
          GIT_SHA: ${{ github.sha }}
          GCP_DOCKER_ARTIFACT_REPO: ${{ vars.GCP_DOCKER_ARTIFACT_REPO }}
        run: pnpm release-processor-images --language=rust --version-tag=${{ github.ref_name }} --wait-for-image-seconds=3600
        working-directory: scripts